language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-kata' ]; then cd .. && eval "mv $currentfolder generator-kata" && cd generator-kata; fi
